import { useState } from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  useState('cool')

  const a = 'asdf'

  if (
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj' ||
    a == 'asdlkfjaslkdfj'
  )
    console.log('good')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App {a}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
